name: List services in GCP
on:
  pull_request:
    branches:
      - main
jobs:
  job_id:
    test_gcp
    permissions:
      - contents: "read"
      - id-token: "write"

    steps:
    # actions/checkout MUST come before auth
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
          workload_identity_provider: ${{secrets.WORKLOAD_IDENTITY_PROVIDER_ID}}
          service_account: ${{secrets.GCP_SERVICE_ACCOUNT}}
