name: List services in GCP
on:
  push:
    branches:
      - main
      
jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          create_credentials_file: true
          workload_identity_provider: projects/291065660416/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider
          service_account: github-actions-service-account@onur-workload-identity-pools.iam.gserviceaccount.com

