name: List services in GCP
on:
  push:
    branches:
      - main
jobs:
  test_GCP:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_ID }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: Print GCP_SERVICE_ACCOUNT
        run: |
          echo "GCP_SERVICE_ACCOUNT: $GCP_SERVICE_ACCOUNT"

#       - name: Authenticate with Google Cloud
#         run: gcloud auth activate-service-account --key-file=${{ secrets.GCP_SERVICE_ACCOUNT }}
#       - name: Configure gcloud with project ID
#         run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        
#       - name: Authenticate with Workload Identity Provider
#         run: |
#           gcloud auth login --update-workload-identity-binding-flag=${{ secrets.WORKLOAD_IDENTITY_PROVIDER_ID }}

      - name: Check authenticated user
        run: gcloud auth list
